### PR TITLE
Add type annotations for all functions

### PR DESCRIPTION
**Pull request by DarwinAwardWinner**
I've written type annotations for every function in the epic module. This allows you to run mypy and type-check the entire codebase. I also fixed a few minor bugs that were revealed by the type checker.

### CODE REVIEW

**Comment by endrebak** [comment]
Thanks. Never used type annotations in Python before. Look forward to
reading PEP484.

There are some typos in your code (typimg), which I guess is why the
continuous integration fails?

It seems like type annotations do not work for 2.7 though. Perhaps they can
be added in a way compatible with 2.7 like shown here:
http://mypy.readthedocs.io/en/latest/python2.html

If you fix that and type annotations does not break anything major, I'll
merge the PR.

Endre

**Comment by DarwinAwardWinner** [comment]
OK, I think I've got everything in order. Let me know if you want me to squash some of the fixup commits before you merge.

**Comment by endrebak** [comment]
Will look closer at this within a few days and before making a new commit
to the project. I am a bit swamped in the beginning of the week. Thanks btw!

**Comment by endrebak** [comment]
Since the tests passed, and the 2.7 version of annotations is really just comments, I merged your PR. Thanks. Added you to the contrib list.

**Pull request merged**
